services:
  - type: web
    name: mywuc
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    rootDir: ./public
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-mywuc
          property: connectionString
      - key: CORS_ALLOW_ORIGIN
        value: '^https?://(localhost|127\.0\.0\.1|arthurdesmonts\.github\.io)(:[0-9]+)?$'
      - key: JWT_SECRET_KEY
        value: /var/www/html/config/jwt/private.pem
      - key: JWT_PUBLIC_KEY
        value: /var/www/html/config/jwt/public.pem
      - key: JWT_PASSPHRASE
        value: ''
    dependencies:
      - name: postgres-mywuc
        type: postgresql
