services:
  - type: web
    name: mywuc
    env: docker
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php bin/console doctrine:migrations:migrate --no-interaction
      php bin/console lexik:jwt:generate-keypair --no-interaction
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-mywuc
          property: connectionString
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_PUBLIC_KEY
        sync: false
      - key: JWT_PASSPHRASE
        sync: false
      - key: CORS_ALLOW_ORIGIN
        value: '^https?://(localhost|127\.0\.0\.1|arthurdesmonts\.github\.io)(:[0-9]+)?$'
    dependencies:
      - name: postgres-mywuc
        type: postgresql
    services:
      - type: web
        name: mywuc
        env: docker
        buildCommand: |
          composer install --no-dev --optimize-autoloader
          php bin/console doctrine:migrations:migrate --no-interaction
        startCommand: apache2-foreground
        envVars:
          - key: APP_ENV
            value: prod
          - key: DATABASE_URL
            fromDatabase:
              name: postgres-mywuc
              property: connectionString